### ISSUE TITLE
Additional interviewer can be removed in Interview  scheduling mail if there are no additional interviewer

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#259]
Description:
Additional interviewer can be removed in Interview scheduling mail if there are no additional interviewer. It is displayed blank now.

<img width="645" alt="additional_interviewer" src="https://user-images.githubusercontent.com/55895538/118237860-b2c02200-b4d2-11eb-9991-f2c114a7414e.png">

**Comment by sandhiyakavi** [comment]
Closing this issue as it can't be removed

**Comment by cagdas001** [comment]
@sandhiyakavi I believe it can be removed. See here for reference: https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/#conditional-statements

And if you decide not to remove it completely, maybe you can show something like "Additional Interviewer: None" if there are no additional interviewers. should be better instead of a blank field
