### ISSUE TITLE
Skills are not displayed in the alphabetical order(A-Z)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#275]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click Select on the skills box
Check the skills tiles

**Expected behavior**
Skills should be sorted alphabetically from-A-to-Z

**Current behavior**
Skills are not sorted alphabetically from-A-to-Z

![image](https://user-images.githubusercontent.com/4592712/119774529-ebeb8f80-bedf-11eb-9bac-ad893ef1018a.png)

**Comment by sexta13** [comment]
This is an issue with the backend. FrontEnd is sending the order by param, but I believe the BE is not taking into consideration the upper and lower case. FE can put an hammer on this, and re-force the sorting....but this should be a responsability from the BE, since it already receives the orderByParam

**Comment by sdgun** [comment]
Verified in Dev.

**Comment by sdgun** [comment]
Verified in production.
