### ISSUE TITLE
Skill search/ JD search is not returning matching roles

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#342]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam/
Click select button in INPUT SKILLS box OR INPUT JOB DESCRIPTION
Select a skill (or enter JD) that matches the skills of an existing role >> click search

**Current behavior**
Only return the custom role

https://user-images.githubusercontent.com/4592712/122837077-1bd85800-d311-11eb-8bcc-ac6c11cee23f.mp4

**Comment by nikolay83** [comment]
@sdgun but it did work on prod last week, right?

**Comment by sdgun** [comment]
@nikolay83 Yes it's working in prod still.

**Comment by nikolay83** [comment]
@urwithat Can it be something with ES index on dev?

**Comment by eisbilir** [comment]
@nikolay83 
> Examples:
requestSkills = {A, B, C} and roleSkills = {C, E, B, F, G} = > skillsMatch is 67%requestSkills = {A} and roleSkills = {A, C, E, B, F, G} = > skillsMatch is 100%
> requestSkills = {A} and roleSkills = {C, E, B, F, G} = > skillsMatch is 0%
> requestSkills = {A, B, C, D} and roleSkills = {A, B, C, F} = > skillsMatch is 75%
> requestSkills = {A, B, C, D} and roleSkills = {A, B, C} = > skillsMatch is 75%

Skills matching logic is working just as you described above.

However, it can't match given skills with role's skills after this commit https://github.com/topcoder-platform/taas-apis/pull/366/commits/eb4afdb9f9fa5866919dae0ddbc2d8e4da6c4f90 because we should not convert the skill names to lowercase. The endpoint accepts roleIds. And role object stores the skills by names in their original form. So we don't need the skill names in lowercase at all, otherwise it can't match.
Here is the fix: topcoder-platform/taas-apis#374

**Comment by nikolay83** [comment]
thank you @eisbilir! I merged it.

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

**Comment by sdgun** [comment]
Verified in production, the issue is fixed.
