### ISSUE TITLE
The Rates show value 10 by default instead of 0

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#439]
Steps
Go to TAAS Admin >> Roles
Click create new role button
Click Add rate and check the default rates

By default 10 is set on all rates instead of 0

https://user-images.githubusercontent.com/4592712/128831713-52a14715-e911-4481-96ef-f8f06c5056a0.mp4

**Comment by cagdas001** [comment]
@sdgun 0 is not a valid value anymore because fields accept only positive integers

**Comment by nikolay83** [comment]
I don't think it's P2 (rather P4) as we would hardly have rates equal or lower than $10/week :) Rather starting from $1000/week.

**Comment by sdgun** [comment]
Hi @nikolay83 @cagdas001 No issue in reducing the priority considering that. But I am wondering since only the Global rate is a mandatory field here the user will have to manually delete all other fields in case if the user doesn't want to set Rate 30/Rate 20 etc. Will it not be useful to keep them empty rather if this is a valid use case?

**Comment by cagdas001** [comment]
Then maybe we should auto-populate only the mandatory fields and should leave blank other fields

**Comment by cagdas001** [comment]
One of the reasons I auto populate them is actually to indicate it's a number field. Because it currently looks like a regular text field (after removing +/- buttons), user may try to input letters instead of numbers. Inputting letters will not result in any error message to let user know about this, what they will see is just a non-working field because what they enter wont be reflected in the field (non numeric chars are not allowed to type)

So we should either indicate in some way (like auto populating some default values) that it's a number field, or allow non-numeric chars as well to be able to type (with error messages on invalid inputs)

I think populating only the default fields also should work to indicate they're numbers...

That's my 2 cents...

**Comment by nikolay83** [comment]
@wdprice 
do you want to set the minimum weekly rate in Admin Roles UI?

**Comment by cagdas001** [comment]
> do you want to set the minimum weekly rate in Admin Roles UI?

Just following on the discussion. Did you mean "default" values, as discussed above? Or you're talking about another thing and "minimum" is the correct term?

**Comment by nikolay83** [comment]
I think the default can be a minimum. Anyway, rates as low as $10/week don't make sense and if displayed to a customer may be even more confusing than "N/A".

**Comment by nikolay83** [comment]
Requirement: just auto-populate all the rates with $1000.

**Comment by sdgun** [comment]
Verified in Dev, fixed.


https://user-images.githubusercontent.com/4592712/129435256-4d5fdacf-295d-45d2-a1c8-0abce5b0bcce.mp4

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129544257-9d6e83bb-04f2-469b-ab64-d8ff8a96cbcf.png)


![image](https://user-images.githubusercontent.com/4592712/129544319-37b6621d-b36c-45d2-a69f-91d8c64ac89d.png)
