### ISSUE TITLE
Interviews are not getting scheduled

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#596]
**Steps**
When the JC schedules the interview using the link sent in the email, the interview is not getting scheduled and no emails on interview are received

https://user-images.githubusercontent.com/4592712/147044288-2e7d5448-7996-4267-b9e4-9eafa43d332c.mp4

**Comment by maxceem** [comment]
@sdgun I wonder if you used Google calendar to schedule this meeting or no calendar?

**Comment by maxceem** [comment]
@sdgun the interview looks scheduled now, maybe it just took a bit longer to complete scheduling, could you please check one more time if got the email?

![image](https://user-images.githubusercontent.com/146016/147056585-c296b8a5-660f-456c-9024-c24a7357ba04.png)

**Comment by sdgun** [comment]
@maxceem Tried with google calender, but I see the interview in scheduled status and emails received after 1.5 hours of scheduling though. I tried scheduling now and it seems to be working now.

**Comment by sdgun** [comment]
Closing since this issue is not recreated anymore

**Comment by maxceem** [comment]
Just for the reference. Here is the timing in log:
- `2021-12-22T05:54:57.550Z` - the interview was scheduled by Customer
- `2021-12-22T05:55:00.159Z` - interview invitation was sent (`InterviewEventHandler sendInterviewInvitationNotifications`)
And only after more than an hour:
- `2021-12-22T07:07:56.208Z` -  got reminder webhook that time was selected (`partiallyUpdateInterviewByWebhook`)
- `2021-12-22T07:08:00.639Z` - send confirmation emails to guest and host

This delay was caused by the time when Nylas sent events to our API.

**Comment by maxceem** [comment]
@sdgun just in case, after you choose time for this interview and email didn't come. Did you try selecting time again one more time somehow for the same interview?

**Comment by sdgun** [comment]
@maxceem Yes, I scheduled another interview after some time to check.

**Comment by maxceem** [comment]
@sdgun to be clear, did you schedule a new interview using customer user? 
Or did you try to choose time again using Job Candidate user for **the same** interview?

**Comment by sdgun** [comment]
@maxceem I scheduled a new interview using customer user
