### ISSUE TITLE
RCRM Job Description Formatting not carrying over

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#74]
When a Job is created in RCRM, no formatting is carried over:

![image](https://user-images.githubusercontent.com/6014049/106338676-640fb480-6262-11eb-846e-47ad282a3533.png)

Need to investigate how we can get that carry across.

**Comment by maxceem** [comment]
This should work well now in both DEV and PROD.

**Comment by sandhiyakavi** [comment]
@maxceem Verified on Dev Env. Everything is fine, except the numbering of the steps which is not highlighted in bold like the bullet point.

<img width="946" alt="dev_jobdescription_2" src="https://user-images.githubusercontent.com/55895538/109109822-5d009700-7779-11eb-90e8-025407981b89.png">
<img width="959" alt="dev_job description" src="https://user-images.githubusercontent.com/55895538/109109839-612cb480-7779-11eb-81dc-29e6b96c08f2.png">

**Comment by maxceem** [comment]
@sandhiyakavi I'm not sure what is the issue from the description above. Cold you please, provide more details on what is expected after which steps.

By the way, I would like to clarify the initial issue here:
1. When we create a job using Connect Intake Form https://connect.topcoder-dev.com/new-project/taas-jobs we can enter description with formatting: 
     ![image](https://user-images.githubusercontent.com/146016/109112766-d382a200-7743-11eb-85a0-fdb8d1b0fefb.png)

2. We expect the formatting that we have there is carried over to the RCRM. Before the formatting has been lost and everything looks like one long line:

    ![image](https://user-images.githubusercontent.com/146016/109112835-f3b26100-7743-11eb-9379-c57a685e964b.png)

3. Now, styles may be different, but in general formatting in RCRM should be similar to what we entered when we created job in Connect Intake form.

**Comment by sandhiyakavi** [comment]
@maxceem please Ignore the above comment.

I verified the issue in both Dev and Prod. Below are some of my observations.

1. Task kind of bullet is not displaying in RCRM.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/55895538/109124756-a4455280-778e-11eb-858f-687834b63e3b.png">

2. Contents copied from Word doc and pasted are not getting aligned.
<img width="960" alt="2" src="https://user-images.githubusercontent.com/55895538/109124880-c50da800-778e-11eb-91eb-b70b519d2271.png">

3. Inline code and Insert block are not getting carried over.
<img width="960" alt="3" src="https://user-images.githubusercontent.com/55895538/109124991-e5d5fd80-778e-11eb-8f2a-f6426fa9d445.png">

4. Table formats are not getting carried over.

<img width="959" alt="4" src="https://user-images.githubusercontent.com/55895538/109124631-7bbd5880-778e-11eb-8419-c11a771ca38e.png">
<img width="960" alt="5" src="https://user-images.githubusercontent.com/55895538/109124642-7f50df80-778e-11eb-890e-8dafd1fda958.png">

In Prod
![image (21)](https://user-images.githubusercontent.com/55895538/109125274-34839780-778f-11eb-879c-bc68debd0ad4.png)

**Comment by maxceem** [comment]
Below are just my comments for now. I would discuss it with WIll.

> 1. Task kind of bullet is not displaying in RCRM.

I think we should remove this option from the Editor, as customers really don't need it.

> 2. Contents copied from Word doc and pasted are not getting aligned.

This issue is more related to the editor https://github.com/topcoder-platform/taas-app/issues/100. In the curren ticket, we only check how good what we enter inside Intake Form is displayed inside RCRM.
Also, we didn't have a requirement to support copy/pasting from the Word doc, though I agree that this is a great feature to have. But I'm not sure if this is possible due to the limitations of the Markdown format.

> 3. Inline code and Insert block are not getting carried over.

They are carried, but the styles which we use inside Editor and inside RCRM are different. So I agree that it's better to update styles in Editor to match what user would see inside the RCRM.

> 4. Table formats are not getting carried over.

This is unfortunate, we have to consider removing this feature from the Editor if we think that we can live without it.

**Comment by maxceem** [comment]
I suggest removing features:

- Table - because cannot be converted properly to RCRM (in theory can, but somehow doesn't work)
- Tasks - because don't need and cannot be displayed in RCRM
- Indent - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097
- Outdnet - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097

Editor before:

![image](https://user-images.githubusercontent.com/146016/109140252-12751f80-7765-11eb-9f5e-1a74ded19d13.png)

After:

![image](https://user-images.githubusercontent.com/146016/109140530-58ca7e80-7765-11eb-8fde-660a0316bff7.png)

**Comment by sandhiyakavi** [comment]
Closing this issue as a separate issue https://github.com/appirio-tech/connect-app/issues/4331 is opened for https://github.com/topcoder-platform/taas-app/issues/74#issuecomment-785792579
